#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Checking for outdated supplemental generated code"
scripts/gen
if ! git diff --exit-code; then
    echo "error: supplemental generated code is out of date" >&2
    echo " hint: run \`scripts/gen\` to regenerate the code" >&2
    exit 1
fi

echo "==> Running lints"

if command -v ktfmt &> /dev/null; then
    echo "==> Checking ktfmt"
    ./scripts/kotlin-format --dry-run --set-exit-if-changed
else
    echo "==> Running gradlew lintKotlin"
    ./gradlew lintKotlin
fi

if command -v palantir-java-format &> /dev/null; then
    echo "==> Checking palantir-java-format"
    ./scripts/java-format --dry-run --set-exit-if-changed
else
    echo "==> Running gradlew lintJava"
    ./gradlew lintJava
fi
