#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."



echo "==> Running tests"
./gradlew test "$@"

for example in turbopuffer-java-example/src/main/java/com/turbopuffer/example/*.java; do
  example=$(basename "$example" .java)
  echo "==> Running $example example"
  ./gradlew run -Pcom.turbopuffer.example=$example
done