// Code generated by turbopuffer-apigen. DO NOT EDIT.

package com.turbopuffer.models.namespaces

import com.fasterxml.jackson.annotation.JsonAutoDetect
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility
import com.fasterxml.jackson.annotation.JsonFormat
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import com.fasterxml.jackson.annotation.JsonValue as JsonValueAnnotation
import com.fasterxml.jackson.core.ObjectCodec
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.fasterxml.jackson.databind.json.JsonMapper
import com.turbopuffer.core.BaseDeserializer
import com.turbopuffer.core.JsonValue
import com.turbopuffer.core.jsonMapper

val jsonMapper: JsonMapper = jsonMapper()

@JsonDeserialize(using = AggregateBy.Deserializer::class)
sealed class AggregateBy() {
    companion object {
        @JvmStatic public fun count(): AggregateByCount = AggregateByCount.create()

        @JvmStatic public fun sum(attr: String): AggregateBySum = AggregateBySum.create(attr)

        @JvmStatic
        public fun count(attr: String): AggregateByCountDeprecated =
            AggregateByCountDeprecated.create(attr)
    }

    class Deserializer : BaseDeserializer<AggregateBy>(AggregateBy::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): AggregateBy {
            return AggregateByRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class AggregateByRaw internal constructor(value: JsonValue) : AggregateBy() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0")
class AggregateByCount private constructor() : AggregateBy() {
    private val f0: String = "Count"

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(): AggregateByCount = AggregateByCount()
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr")
class AggregateByCountDeprecated private constructor(attr: String) : AggregateBy() {
    private val f0: String = "Count"
    private val attr: String = attr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String): AggregateByCountDeprecated =
            AggregateByCountDeprecated(attr)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr")
class AggregateBySum private constructor(attr: String) : AggregateBy() {
    private val f0: String = "Sum"
    private val attr: String = attr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(attr: String): AggregateBySum = AggregateBySum(attr)
    }
}

@JsonDeserialize(using = ComputeAttributes.Deserializer::class)
sealed class ComputeAttributes() {
    companion object {
        @JvmStatic
        public fun vectorDist(attr: String, value: List<Float>): ComputeAttributesVectorDist =
            ComputeAttributesVectorDist.create(attr, value)

        @JvmStatic
        public fun highlight(attr: String): ComputeAttributesHighlight =
            ComputeAttributesHighlight.create(attr)

        @JvmStatic
        public fun highlight(
            attr: String,
            config: HighlightConfigParams,
        ): ComputeAttributesHighlightWithConfig =
            ComputeAttributesHighlightWithConfig.create(attr, config)
    }

    class Deserializer : BaseDeserializer<ComputeAttributes>(ComputeAttributes::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): ComputeAttributes {
            return ComputeAttributesRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class ComputeAttributesRaw internal constructor(value: JsonValue) : ComputeAttributes() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr")
class ComputeAttributesHighlight private constructor(attr: String) : ComputeAttributes() {
    private val f0: String = "Highlight"
    private val attr: String = attr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String): ComputeAttributesHighlight =
            ComputeAttributesHighlight(attr)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr", "config")
class ComputeAttributesHighlightWithConfig
private constructor(attr: String, config: HighlightConfigParams) : ComputeAttributes() {
    private val f0: String = "Highlight"
    private val attr: String = attr
    private val config: HighlightConfigParams = config

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            config: HighlightConfigParams,
        ): ComputeAttributesHighlightWithConfig = ComputeAttributesHighlightWithConfig(attr, config)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class ComputeAttributesVectorDist private constructor(attr: String, value: List<Float>) :
    ComputeAttributes() {
    private val attr: String = attr
    private val f0: String = "VectorDist"
    private val value: List<Float> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Float>): ComputeAttributesVectorDist =
            ComputeAttributesVectorDist(attr, value)
    }
}

@JsonDeserialize(using = Expr.Deserializer::class)
sealed class Expr() {
    companion object {
        @JvmStatic public fun refNew(refNew: String): ExprRefNew = ExprRefNew.create(refNew)

        @JvmStatic public fun embed(value: String): ExprEmbed = ExprEmbed.create(value)

        @JvmStatic
        public fun embed(value: String, params: EmbedParams): ExprEmbedWithParams =
            ExprEmbedWithParams.create(value, params)
    }

    class Deserializer : BaseDeserializer<Expr>(Expr::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): Expr {
            return ExprRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class ExprRaw internal constructor(value: JsonValue) : Expr() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "value")
class ExprEmbed private constructor(value: String) : Expr() {
    private val f0: String = "Embed"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(value: String): ExprEmbed = ExprEmbed(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "value", "params")
class ExprEmbedWithParams private constructor(value: String, params: EmbedParams) : Expr() {
    private val f0: String = "Embed"
    private val value: String = value
    private val params: EmbedParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(value: String, params: EmbedParams): ExprEmbedWithParams =
            ExprEmbedWithParams(value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonPropertyOrder("refNew")
class ExprRefNew private constructor(refNew: String) : Expr() {
    @JsonProperty("\$ref_new") private val refNew: String = refNew

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(refNew: String): ExprRefNew = ExprRefNew(refNew)
    }
}

@JsonDeserialize(using = Filter.Deserializer::class)
sealed class Filter() : RankByText() {
    companion object {
        @JvmStatic public fun eq(attr: String, value: Any): FilterEq = FilterEq.create(attr, value)

        @JvmStatic
        public fun notEq(attr: String, value: Any): FilterNotEq = FilterNotEq.create(attr, value)

        @JvmStatic
        public fun `in`(attr: String, value: List<Any>): FilterIn = FilterIn.create(attr, value)

        @JvmStatic
        public fun notIn(attr: String, value: List<Any>): FilterNotIn =
            FilterNotIn.create(attr, value)

        @JvmStatic
        public fun contains(attr: String, value: Any): FilterContains =
            FilterContains.create(attr, value)

        @JvmStatic
        public fun notContains(attr: String, value: Any): FilterNotContains =
            FilterNotContains.create(attr, value)

        @JvmStatic
        public fun containsAny(attr: String, value: List<Any>): FilterContainsAny =
            FilterContainsAny.create(attr, value)

        @JvmStatic
        public fun notContainsAny(attr: String, value: List<Any>): FilterNotContainsAny =
            FilterNotContainsAny.create(attr, value)

        @JvmStatic public fun lt(attr: String, value: Any): FilterLt = FilterLt.create(attr, value)

        @JvmStatic
        public fun lte(attr: String, value: Any): FilterLte = FilterLte.create(attr, value)

        @JvmStatic public fun gt(attr: String, value: Any): FilterGt = FilterGt.create(attr, value)

        @JvmStatic
        public fun gte(attr: String, value: Any): FilterGte = FilterGte.create(attr, value)

        @JvmStatic
        public fun anyLt(attr: String, value: Any): FilterAnyLt = FilterAnyLt.create(attr, value)

        @JvmStatic
        public fun anyLte(attr: String, value: Any): FilterAnyLte = FilterAnyLte.create(attr, value)

        @JvmStatic
        public fun anyGt(attr: String, value: Any): FilterAnyGt = FilterAnyGt.create(attr, value)

        @JvmStatic
        public fun anyGte(attr: String, value: Any): FilterAnyGte = FilterAnyGte.create(attr, value)

        @JvmStatic
        public fun glob(attr: String, value: String): FilterGlob = FilterGlob.create(attr, value)

        @JvmStatic
        public fun notGlob(attr: String, value: String): FilterNotGlob =
            FilterNotGlob.create(attr, value)

        @JvmStatic
        public fun iGlob(attr: String, value: String): FilterIGlob = FilterIGlob.create(attr, value)

        @JvmStatic
        public fun notIGlob(attr: String, value: String): FilterNotIGlob =
            FilterNotIGlob.create(attr, value)

        @JvmStatic
        public fun regex(attr: String, value: String): FilterRegex = FilterRegex.create(attr, value)

        @JvmStatic
        public fun fuzzy(attr: String, value: String, params: FuzzyParams): FilterFuzzy =
            FilterFuzzy.create(attr, value, params)

        @JvmStatic
        public fun containsAllTokens(attr: String, value: String): FilterContainsAllTokens =
            FilterContainsAllTokens.create(attr, value)

        @JvmStatic
        public fun containsAllTokens(
            attr: String,
            value: List<String>,
        ): FilterContainsAllTokensArray = FilterContainsAllTokensArray.create(attr, value)

        @JvmStatic
        public fun containsAllTokens(
            attr: String,
            value: String,
            params: ContainsAllTokensFilterParams,
        ): FilterContainsAllTokensWithParams =
            FilterContainsAllTokensWithParams.create(attr, value, params)

        @JvmStatic
        public fun containsAllTokens(
            attr: String,
            value: List<String>,
            params: ContainsAllTokensFilterParams,
        ): FilterContainsAllTokensArrayWithParams =
            FilterContainsAllTokensArrayWithParams.create(attr, value, params)

        @JvmStatic
        public fun containsAnyToken(attr: String, value: String): FilterContainsAnyToken =
            FilterContainsAnyToken.create(attr, value)

        @JvmStatic
        public fun containsAnyToken(
            attr: String,
            value: List<String>,
        ): FilterContainsAnyTokenArray = FilterContainsAnyTokenArray.create(attr, value)

        @JvmStatic
        public fun containsAnyToken(
            attr: String,
            value: String,
            params: ContainsAnyTokenFilterParams,
        ): FilterContainsAnyTokenWithParams =
            FilterContainsAnyTokenWithParams.create(attr, value, params)

        @JvmStatic
        public fun containsAnyToken(
            attr: String,
            value: List<String>,
            params: ContainsAnyTokenFilterParams,
        ): FilterContainsAnyTokenArrayWithParams =
            FilterContainsAnyTokenArrayWithParams.create(attr, value, params)

        @JvmStatic
        public fun containsTokenSequence(attr: String, value: String): FilterContainsTokenSequence =
            FilterContainsTokenSequence.create(attr, value)

        @JvmStatic
        public fun containsTokenSequence(
            attr: String,
            value: List<String>,
        ): FilterContainsTokenSequenceArray = FilterContainsTokenSequenceArray.create(attr, value)

        @JvmStatic public fun not(filter: Filter): FilterNot = FilterNot.create(filter)

        @JvmStatic
        public fun and(vararg filters: Filter): FilterAnd = FilterAnd.create(filters.asList())

        @JvmStatic
        public fun or(vararg filters: Filter): FilterOr = FilterOr.create(filters.asList())
    }

    class Deserializer : BaseDeserializer<Filter>(Filter::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): Filter {
            return FilterRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class FilterRaw internal constructor(value: JsonValue) : Filter() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "filters")
class FilterAnd private constructor(filters: List<Filter>) : Filter() {
    private val f0: String = "And"
    private val filters: List<Filter> = filters

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(filters: List<Filter>): FilterAnd = FilterAnd(filters)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterAnyGt private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "AnyGt"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterAnyGt = FilterAnyGt(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterAnyGte private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "AnyGte"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterAnyGte = FilterAnyGte(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterAnyLt private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "AnyLt"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterAnyLt = FilterAnyLt(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterAnyLte private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "AnyLte"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterAnyLte = FilterAnyLte(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContains private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Contains"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterContains = FilterContains(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsAllTokens private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAllTokens"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterContainsAllTokens =
            FilterContainsAllTokens(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsAllTokensArray private constructor(attr: String, value: List<String>) :
    Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAllTokens"
    private val value: List<String> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<String>): FilterContainsAllTokensArray =
            FilterContainsAllTokensArray(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class FilterContainsAllTokensArrayWithParams
private constructor(attr: String, value: List<String>, params: ContainsAllTokensFilterParams) :
    Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAllTokens"
    private val value: List<String> = value
    private val params: ContainsAllTokensFilterParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: List<String>,
            params: ContainsAllTokensFilterParams,
        ): FilterContainsAllTokensArrayWithParams =
            FilterContainsAllTokensArrayWithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class FilterContainsAllTokensWithParams
private constructor(attr: String, value: String, params: ContainsAllTokensFilterParams) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAllTokens"
    private val value: String = value
    private val params: ContainsAllTokensFilterParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: String,
            params: ContainsAllTokensFilterParams,
        ): FilterContainsAllTokensWithParams =
            FilterContainsAllTokensWithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsAny private constructor(attr: String, value: List<Any>) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAny"
    private val value: List<Any> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Any>): FilterContainsAny =
            FilterContainsAny(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsAnyToken private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAnyToken"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterContainsAnyToken =
            FilterContainsAnyToken(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsAnyTokenArray private constructor(attr: String, value: List<String>) :
    Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAnyToken"
    private val value: List<String> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<String>): FilterContainsAnyTokenArray =
            FilterContainsAnyTokenArray(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class FilterContainsAnyTokenArrayWithParams
private constructor(attr: String, value: List<String>, params: ContainsAnyTokenFilterParams) :
    Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAnyToken"
    private val value: List<String> = value
    private val params: ContainsAnyTokenFilterParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: List<String>,
            params: ContainsAnyTokenFilterParams,
        ): FilterContainsAnyTokenArrayWithParams =
            FilterContainsAnyTokenArrayWithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class FilterContainsAnyTokenWithParams
private constructor(attr: String, value: String, params: ContainsAnyTokenFilterParams) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsAnyToken"
    private val value: String = value
    private val params: ContainsAnyTokenFilterParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: String,
            params: ContainsAnyTokenFilterParams,
        ): FilterContainsAnyTokenWithParams = FilterContainsAnyTokenWithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsTokenSequence private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsTokenSequence"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterContainsTokenSequence =
            FilterContainsTokenSequence(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterContainsTokenSequenceArray private constructor(attr: String, value: List<String>) :
    Filter() {
    private val attr: String = attr
    private val f0: String = "ContainsTokenSequence"
    private val value: List<String> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<String>): FilterContainsTokenSequenceArray =
            FilterContainsTokenSequenceArray(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterEq private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Eq"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterEq = FilterEq(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class FilterFuzzy private constructor(attr: String, value: String, params: FuzzyParams) : Filter() {
    private val attr: String = attr
    private val f0: String = "Fuzzy"
    private val value: String = value
    private val params: FuzzyParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String, params: FuzzyParams): FilterFuzzy =
            FilterFuzzy(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterGlob private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "Glob"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterGlob = FilterGlob(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterGt private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Gt"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterGt = FilterGt(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterGte private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Gte"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterGte = FilterGte(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterIGlob private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "IGlob"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterIGlob = FilterIGlob(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterIn private constructor(attr: String, value: List<Any>) : Filter() {
    private val attr: String = attr
    private val f0: String = "In"
    private val value: List<Any> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Any>): FilterIn = FilterIn(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterLt private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Lt"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterLt = FilterLt(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterLte private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "Lte"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterLte = FilterLte(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "filter")
class FilterNot private constructor(filter: Filter) : Filter() {
    private val f0: String = "Not"
    private val filter: Filter = filter

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(filter: Filter): FilterNot = FilterNot(filter)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotContains private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotContains"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterNotContains =
            FilterNotContains(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotContainsAny private constructor(attr: String, value: List<Any>) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotContainsAny"
    private val value: List<Any> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Any>): FilterNotContainsAny =
            FilterNotContainsAny(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotEq private constructor(attr: String, value: Any) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotEq"
    private val value: JsonValue = JsonValue.from(value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Any): FilterNotEq = FilterNotEq(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotGlob private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotGlob"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterNotGlob = FilterNotGlob(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotIGlob private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotIGlob"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterNotIGlob =
            FilterNotIGlob(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterNotIn private constructor(attr: String, value: List<Any>) : Filter() {
    private val attr: String = attr
    private val f0: String = "NotIn"
    private val value: List<Any> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Any>): FilterNotIn = FilterNotIn(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "filters")
class FilterOr private constructor(filters: List<Filter>) : Filter() {
    private val f0: String = "Or"
    private val filters: List<Filter> = filters

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(filters: List<Filter>): FilterOr = FilterOr(filters)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class FilterRegex private constructor(attr: String, value: String) : Filter() {
    private val attr: String = attr
    private val f0: String = "Regex"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): FilterRegex = FilterRegex(attr, value)
    }
}

@JsonDeserialize(using = GroupBy.Deserializer::class)
sealed class GroupBy() {
    companion object {
        @JvmStatic public fun attr(value: String): GroupByAttr = GroupByAttr.create(value)

        @JvmStatic
        public fun expr(name: String, value: GroupByFunction): GroupByExpr =
            GroupByExpr.create(name, value)
    }

    class Deserializer : BaseDeserializer<GroupBy>(GroupBy::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): GroupBy {
            return GroupByRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class GroupByRaw internal constructor(value: JsonValue) : GroupBy() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

class GroupByAttr private constructor(value: String) : GroupBy() {
    @JsonValueAnnotation private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }

    companion object {
        @JvmSynthetic internal fun create(value: String): GroupByAttr = GroupByAttr(value)
    }
}

class GroupByExpr private constructor(name: String, value: GroupByFunction) : GroupBy() {
    @JsonValueAnnotation private val data: Map<String, GroupByFunction> = mapOf(name to value)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(data)
    }

    companion object {
        @JvmSynthetic
        internal fun create(name: String, value: GroupByFunction): GroupByExpr =
            GroupByExpr(name, value)
    }
}

@JsonDeserialize(using = GroupByFunction.Deserializer::class)
sealed class GroupByFunction() {
    companion object {
        @JvmStatic
        public fun forEachUnique(attr: String): GroupByFunctionForEachUnique =
            GroupByFunctionForEachUnique.create(attr)
    }

    class Deserializer : BaseDeserializer<GroupByFunction>(GroupByFunction::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): GroupByFunction {
            return GroupByFunctionRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class GroupByFunctionRaw internal constructor(value: JsonValue) : GroupByFunction() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr")
class GroupByFunctionForEachUnique private constructor(attr: String) : GroupByFunction() {
    private val f0: String = "ForEachUnique"
    private val attr: String = attr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String): GroupByFunctionForEachUnique =
            GroupByFunctionForEachUnique(attr)
    }
}

@JsonDeserialize(using = RankBy.Deserializer::class)
sealed class RankBy() : ComputeAttributes() {
    companion object {
        @JvmStatic
        public fun ann(attr: String, value: List<Float>): RankByAnn = RankByAnn.create(attr, value)

        @JvmStatic
        public fun ann(attr: String, value: List<List<Float>>): RankByAnnMulti =
            RankByAnnMulti.create(attr, value)

        @JvmStatic
        public fun ann(attr: String, expr: Expr): RankByAnnExpr = RankByAnnExpr.create(attr, expr)

        @JvmStatic
        public fun knn(attr: String, value: List<Float>): RankByKnn = RankByKnn.create(attr, value)

        @JvmStatic
        public fun knn(attr: String, value: List<List<Float>>): RankByKnnMulti =
            RankByKnnMulti.create(attr, value)

        @JvmStatic
        public fun knn(attr: String, expr: Expr): RankByKnnExpr = RankByKnnExpr.create(attr, expr)

        @JvmStatic
        public fun sparseKnn(attr: String, value: Map<String, Double>): RankBySparseKnn =
            RankBySparseKnn.create(attr, value)

        @JvmStatic
        public fun attribute(attr: String, order: RankByAttributeOrder): RankByAttribute =
            RankByAttribute.create(attr, order)

        @JvmStatic
        public fun attributes(vararg items: RankByAttribute): RankByAttributes =
            RankByAttributes.create(items.asList())
    }

    class Deserializer : BaseDeserializer<RankBy>(RankBy::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): RankBy {
            return RankByRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class RankByRaw internal constructor(value: JsonValue) : RankBy() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByAnn private constructor(attr: String, value: List<Float>) : RankBy() {
    private val attr: String = attr
    private val f0: String = "ANN"
    private val value: List<Float> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Float>): RankByAnn = RankByAnn(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "expr")
class RankByAnnExpr private constructor(attr: String, expr: Expr) : RankBy() {
    private val attr: String = attr
    private val f0: String = "ANN"
    private val expr: Expr = expr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, expr: Expr): RankByAnnExpr = RankByAnnExpr(attr, expr)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByAnnMulti private constructor(attr: String, value: List<List<Float>>) : RankBy() {
    private val attr: String = attr
    private val f0: String = "ANN"
    private val value: List<List<Float>> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<List<Float>>): RankByAnnMulti =
            RankByAnnMulti(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "order")
class RankByAttribute private constructor(attr: String, order: RankByAttributeOrder) : RankBy() {
    private val attr: String = attr
    private val order: RankByAttributeOrder = order

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, order: RankByAttributeOrder): RankByAttribute =
            RankByAttribute(attr, order)
    }
}

enum class RankByAttributeOrder {
    @JsonProperty("asc") ASC,
    @JsonProperty("desc") DESC,
}

class RankByAttributes
private constructor(@JsonValueAnnotation private val items: List<RankByAttribute>) : RankBy() {
    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(items: List<RankByAttribute>): RankByAttributes =
            RankByAttributes(items)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByKnn private constructor(attr: String, value: List<Float>) : RankBy() {
    private val attr: String = attr
    private val f0: String = "kNN"
    private val value: List<Float> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<Float>): RankByKnn = RankByKnn(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "expr")
class RankByKnnExpr private constructor(attr: String, expr: Expr) : RankBy() {
    private val attr: String = attr
    private val f0: String = "kNN"
    private val expr: Expr = expr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, expr: Expr): RankByKnnExpr = RankByKnnExpr(attr, expr)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByKnnMulti private constructor(attr: String, value: List<List<Float>>) : RankBy() {
    private val attr: String = attr
    private val f0: String = "kNN"
    private val value: List<List<Float>> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<List<Float>>): RankByKnnMulti =
            RankByKnnMulti(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankBySparseKnn private constructor(attr: String, value: Map<String, Double>) : RankBy() {
    private val attr: String = attr
    private val f0: String = "SparseKNN"
    private val value: Map<String, Double> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: Map<String, Double>): RankBySparseKnn =
            RankBySparseKnn(attr, value)
    }
}

@JsonDeserialize(using = RankByText.Deserializer::class)
sealed class RankByText() : RankBy() {
    companion object {
        @JvmStatic
        public fun bm25(attr: String, value: String): RankByTextBM25 =
            RankByTextBM25.create(attr, value)

        @JvmStatic
        public fun bm25(attr: String, value: List<String>): RankByTextBM25Array =
            RankByTextBM25Array.create(attr, value)

        @JvmStatic
        public fun bm25(
            attr: String,
            value: String,
            params: Bm25ClauseParams,
        ): RankByTextBM25WithParams = RankByTextBM25WithParams.create(attr, value, params)

        @JvmStatic
        public fun bm25(
            attr: String,
            value: List<String>,
            params: Bm25ClauseParams,
        ): RankByTextBM25ArrayWithParams = RankByTextBM25ArrayWithParams.create(attr, value, params)

        @JvmStatic
        public fun sum(vararg subqueries: RankByText): RankByTextSum =
            RankByTextSum.create(subqueries.asList())

        @JvmStatic
        public fun max(vararg subqueries: RankByText): RankByTextMax =
            RankByTextMax.create(subqueries.asList())

        @JvmStatic
        public fun product(weight: Double, subquery: RankByText): RankByTextProduct =
            RankByTextProduct.create(weight, subquery)

        @JvmStatic
        public fun product(subquery: RankByText, weight: Double): RankByTextProduct2 =
            RankByTextProduct2.create(subquery, weight)

        @JvmStatic
        public fun attribute(attr: String): RankByTextAttribute = RankByTextAttribute.create(attr)

        @JvmStatic
        public fun saturate(subquery: RankByText, params: SaturateParams): RankByTextSaturate =
            RankByTextSaturate.create(subquery, params)

        @JvmStatic
        public fun decay(subquery: RankByText, params: DecayParams): RankByTextDecay =
            RankByTextDecay.create(subquery, params)

        @JvmStatic
        public fun dist(subquery: RankByText, origin: Any): RankByTextDist =
            RankByTextDist.create(subquery, origin)
    }

    class Deserializer : BaseDeserializer<RankByText>(RankByText::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): RankByText {
            return RankByTextRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class RankByTextRaw internal constructor(value: JsonValue) : RankByText() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "attr")
class RankByTextAttribute private constructor(attr: String) : RankByText() {
    private val f0: String = "Attribute"
    private val attr: String = attr

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String): RankByTextAttribute = RankByTextAttribute(attr)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByTextBM25 private constructor(attr: String, value: String) : RankByText() {
    private val attr: String = attr
    private val f0: String = "BM25"
    private val value: String = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: String): RankByTextBM25 =
            RankByTextBM25(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value")
class RankByTextBM25Array private constructor(attr: String, value: List<String>) : RankByText() {
    private val attr: String = attr
    private val f0: String = "BM25"
    private val value: List<String> = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(attr: String, value: List<String>): RankByTextBM25Array =
            RankByTextBM25Array(attr, value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class RankByTextBM25ArrayWithParams
private constructor(attr: String, value: List<String>, params: Bm25ClauseParams) : RankByText() {
    private val attr: String = attr
    private val f0: String = "BM25"
    private val value: List<String> = value
    private val params: Bm25ClauseParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: List<String>,
            params: Bm25ClauseParams,
        ): RankByTextBM25ArrayWithParams = RankByTextBM25ArrayWithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("attr", "f0", "value", "params")
class RankByTextBM25WithParams
private constructor(attr: String, value: String, params: Bm25ClauseParams) : RankByText() {
    private val attr: String = attr
    private val f0: String = "BM25"
    private val value: String = value
    private val params: Bm25ClauseParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(
            attr: String,
            value: String,
            params: Bm25ClauseParams,
        ): RankByTextBM25WithParams = RankByTextBM25WithParams(attr, value, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subquery", "params")
class RankByTextDecay private constructor(subquery: RankByText, params: DecayParams) :
    RankByText() {
    private val f0: String = "Decay"
    private val subquery: RankByText = subquery
    private val params: DecayParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subquery: RankByText, params: DecayParams): RankByTextDecay =
            RankByTextDecay(subquery, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subquery", "origin")
class RankByTextDist private constructor(subquery: RankByText, origin: Any) : RankByText() {
    private val f0: String = "Dist"
    private val subquery: RankByText = subquery
    private val origin: JsonValue = JsonValue.from(origin)

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subquery: RankByText, origin: Any): RankByTextDist =
            RankByTextDist(subquery, origin)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subqueries")
class RankByTextMax private constructor(subqueries: List<RankByText>) : RankByText() {
    private val f0: String = "Max"
    private val subqueries: List<RankByText> = subqueries

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subqueries: List<RankByText>): RankByTextMax = RankByTextMax(subqueries)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "weight", "subquery")
class RankByTextProduct private constructor(weight: Double, subquery: RankByText) : RankByText() {
    private val f0: String = "Product"
    private val weight: Double = weight
    private val subquery: RankByText = subquery

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(weight: Double, subquery: RankByText): RankByTextProduct =
            RankByTextProduct(weight, subquery)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subquery", "weight")
class RankByTextProduct2 private constructor(subquery: RankByText, weight: Double) : RankByText() {
    private val f0: String = "Product"
    private val subquery: RankByText = subquery
    private val weight: Double = weight

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subquery: RankByText, weight: Double): RankByTextProduct2 =
            RankByTextProduct2(subquery, weight)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subquery", "params")
class RankByTextSaturate private constructor(subquery: RankByText, params: SaturateParams) :
    RankByText() {
    private val f0: String = "Saturate"
    private val subquery: RankByText = subquery
    private val params: SaturateParams = params

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subquery: RankByText, params: SaturateParams): RankByTextSaturate =
            RankByTextSaturate(subquery, params)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "subqueries")
class RankByTextSum private constructor(subqueries: List<RankByText>) : RankByText() {
    private val f0: String = "Sum"
    private val subqueries: List<RankByText> = subqueries

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(subqueries: List<RankByText>): RankByTextSum = RankByTextSum(subqueries)
    }
}

@JsonDeserialize(using = RerankBy.Deserializer::class)
sealed class RerankBy() {
    companion object {
        @JvmStatic public fun rrf(): RerankByRrf = RerankByRrf.create()

        @JvmStatic
        public fun rrf(f1: RrfParams): RerankByRrfWithParams = RerankByRrfWithParams.create(f1)
    }

    class Deserializer : BaseDeserializer<RerankBy>(RerankBy::class) {
        override fun ObjectCodec.deserialize(node: JsonNode): RerankBy {
            return RerankByRaw(JsonValue.fromJsonNode(node))
        }
    }
}

class RerankByRaw internal constructor(value: JsonValue) : RerankBy() {
    @JsonValueAnnotation private val value: JsonValue = value

    override fun toString(): String {
        return jsonMapper.writeValueAsString(value)
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0")
class RerankByRrf private constructor() : RerankBy() {
    private val f0: String = "RRF"

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic internal fun create(): RerankByRrf = RerankByRrf()
    }
}

@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonFormat(shape = JsonFormat.Shape.ARRAY)
@JsonPropertyOrder("f0", "f1")
class RerankByRrfWithParams private constructor(f1: RrfParams) : RerankBy() {
    private val f0: String = "RRF"
    private val f1: RrfParams = f1

    override fun toString(): String {
        return jsonMapper.writeValueAsString(this)
    }

    companion object {
        @JvmSynthetic
        internal fun create(f1: RrfParams): RerankByRrfWithParams = RerankByRrfWithParams(f1)
    }
}
